sections/shopify-login.liquid

Change the redirect destination after logging in to whatever we get from FBolt. 
This is expected to be a multipass url with a `return_to` set. This allows us to direct the user to a destination on Shopify while also logging them in.

Fix login redirect

---

layout/checkout.liquid
layout/theme.liquid

Installs the JS snippets for our Google Tag Manager container. 
This should restore firing of some tags that were disrupted when we migrated to Shopify's checkout.
I followed steps 1-6 in this [Shopify help article](https://help.shopify.com/en/manual/reports-and-analytics/google-analytics/google-tag-manager#add-google-tag-manager-code-to-your-theme).
After deploying, we will need to reconfigure the `XCP-Adwords_Purchase` tag in TagManager. Specifically, we will need to create or refactor the `XCP-orderSubmit` Trigger for this tag:

Install Google Tag Manager snippets

---

layout/checkout.liquid
layout/theme.liquid

* Only render Google Tag Manager snippet in production or staging
* Toggle the correct GTM Container ID
Updates `theme.liquid` and `checkout.liquid` to render the correct GTM snippet depending on the environment.
Without this, Staging (and possibly Development, and even the Shopify Theme Editor previews) could send data to Google Tag Manager. This is probably not consequential but we don't want to muddy the waters if we can avoid it.

Install environment-dependent Google Tag Manager snippets

---

layout/checkout.liquid
snippets/google-data-layer-ecommerce-add-shipping-info.liquid
snippets/google-data-layer-ecommerce-begin-checkout.liquid
snippets/google-data-layer-ecommerce-purchase.liquid

Adds a `skus` property to the ecommerce objects pushed to the dataLayer
(Technically, this is only used when the `purchase` event occurs, but it could be useful for other events in the checkout flow.)
This is needed to enable conversion tracking in Google Ads via Google Tag Manager.
By adding `skus`, we can access them in Google Tag Manager:
We can then create a GTM Trigger to check for the presence of a specific SKU. For example, this Trigger can be used to fire a Tag when a customer is checking out with an X-Carve Pro:
With this Trigger, we can create the appropriate Google Ads Conversion Tracking Tag so that we can track XCP conversions in Google Ads and measure the performance of our ad campaigns.
Apparently it's not possible to directly assign an array to a liquid variable, so I map …

Add distinct skus to dataLayer ecommerce objects

---

sections/featured-product.liquid
sections/main-product.liquid

This Liquid is responsible for rendering the "From $X/mo with Shop Pay" banner that appears on product pages.
```
{{ form | payment_terms }}
```
This is not accessible in the Theme Editor, so in order to change it we need to modify this theme code.
See: https://help.shopify.com/en/manual/payments/shop-pay-installments/product-banner

Hide Shop Pay banner from all product pages

---

templates/product.x-carve-pro-product-page.json

Minor adjustments to the X-Carve Pro product page:
* Remove Clyde protection plan checkbox placeholder
* Adjust margins of 'You will need...'
* Adjust margins and flex spacing of 'Details'
**Screenshots**
**Full page screenshot for reference**

X-Carve Pro product page adjustments

---

templates/product.x-carve-pro-product-page.json

* Split product media and product info sections 50/50 within the container.
* Add size "buttons"
* 4x4 button won't do anything
* 4x2 is an `<a></a>` that will link to the not-yet-imported 4x2 product

Further improvements to X-Carve Pro 4x4 product page template

---

templates/collection.json

There seems to be an issue with our current version of the Dawn theme (or how we're using it).
I'm not certain if this is the culprit, but the CSS `calc` function for the .card__media width is resulting in `0`, when I expect it to be `100%`:
Even when I set the custom CSS to the exact same value using `calc`, the result is 100%. This makes me think something else is messing with the width.
```
calc(100% - 2 * var(--image-padding))
var(--image-padding) is 0.0 rem, so 100% - 2 * 0 should equal 100%
```
I explicitly set the width to 100% in the Custom CSS section of the collections template.
Specifically, go to Collections > Default Collection > Product Grid
On the right sidebar scroll to the bottom.
https://github.com/inventables/ecomm-theme-dawn/assets/26750330/b54496fb-5c6f-4a53-bb3b-b17e5 …

Override CSS width to fix bug with images on collection pages

---

assets/global.js
assets/inventables.js
layout/inventables.liquid
layout/theme.liquid
sections/main-product.liquid

This PR includes logic to hide any variants that are unavailable for purchase. 
This was complicated by the fact that Dawn doesn't list variants explicitly on the product page. 
Instead, it lists the _options_ made available by those variants (e.g., size, color, etc), when when those options are selected, it looks for a variant that matches that combination of options. If such a variant does not exist, the "add to cart" button is disabled. 
We want to extend that behavior to consider any unavailable variants as unavailable in the above logic (finding the variant that matches the selected options). We also want to hide any options for which _no_ variants are available. (For example, if we sell something that comes in red, yellow, and green, but all the green variants are disabled, we also …

Hide variants

---

sections/shopify-login.liquid

I noticed that the login page was loading really slowly. This PR addresses that. 
On investigation, the login page is loading a lot of assets (including a large video), and the iframe contents w/ the username and password weren't loading until after those. It would sometimes take a few seconds before the login form appeared, and it would appear that the page was broken. 
This PR addresses that problem by moving the loading of the iframe contents to earlier in the page load process so we don't wait until all the assets (fonts, CSS, videos, etc) are loading before doing so. 
In testing, the second item made a big difference in the page load experience.

load login iframe earlier in the page lifecycle

---

layout/theme.liquid

This adds a snippet that enables Google Ads conversion tracking on all web pages.
This follows the guide at https://help.shopify.com/en/manual/promoting-marketing/analyze-marketing/tracking-adwords-conversions

added tag for google ads to work

---

assets/inventables.js

When `variantRadios` comes back as `undefined` the script breaks and somehow interferes with Google tracking for add to cart events.

fixes an undefined error

---

layout/theme.liquid
layout/xcp.liquid

We thought this was deprecated, but I think only the `checkout.liquid` is deprecated and `theme.liquid` still needs the snippet in order for GTM to work.

Add GTM snippet back into `theme.liquid`

---

sections/xcp-video.liquid

Remove "cover_image" setting from xcp-video.
Poster is set through Vimeo.

Remove "cover_image" setting from xcp-video

---

sections/inv-product.liquid
snippets/inv-product-thumbnail.liquid

This issue was caused by cd85b92b63b3b8ecbea51e52b5531711adb266e0 . It modified a snippet used by both 'general product page' and 'xcp product pages'.
I've duplicated the 'product-thumbnail' snippet and used its duplicate, 'inv-product-thumbnail', on 'inv-product' section. 
This changes contain new wrapper element only to the 'general product page', fixing XCP pages.

Fix image hidden on XCP product pages

---

assets/section-footer.css
sections/footer.liquid

**What this PR does**
Replaces the footer bottom content with a simpler design
**Context**
I noticed the privacy policy and terms of use links were incorrect. While working on this I wanted to redo this section because the style is less than ideal.
**How to test**
I tested this on my machine against my development store by running `shopify theme serve`. I then connected this branch to the production store and previewed the theme:

Replace footer bottom content with simpler styling

---

sections/xcp-product.liquid
snippets/xcp-affirm.liquid
snippets/xcp-price.liquid
templates/product.x-carve-product.json

update affirm text regarding financing for XC by using text from xcp-price settings
XC text needed to be removed,  but we wanted this field to be able to be edited from the theme editor

Make Xcp affirm financing editable in the theme editor

---

config/settings_schema.json
sections/header.liquid

1. Sets `admin = true` if the user is logged in and the customer object is tagged with "admin"
2. Adds a theme setting so it's easier to test UI that depends on whether a customer is logged in and whether they are an admin
Fixes https://github.com/inventables/fbolt/issues/6293
The gear icon that toggles the admin link dropdown stopped showing because our admin check (`CFH contains 'admin_bar_iframe'`) stopped working. 
Unfortunately, this was the suggestion in the [most popular support article on the topic](https://community.shopify.com/c/technical-q-a/detect-admin-shop-owner-logged-into-store/m-p/2069680/highlight/true#M127659) and this [related SO post](https://stackoverflow.com/questions/17470921/how-to-check-if-current-visitor-is-shops-admin).
I also chatted with Shopify Plus Support, …

Set logged_in and admin variables in the header

---

config/settings_data.json
sections/easel-all-in-one.liquid
sections/easel-plans.liquid
sections/easel-supported-hardware.liquid

**What does this PR do?**
^^
**Background Context and Screenshots**
After merging #81 and checking the links, I noticed we are missing IDs for these links to anchor to:
**What steps did you take to test your changes?**
https://github.com/inventables/ecomm-theme-dawn/assets/26750330/131fa884-930b-4fed-8f66-4401fd4d0811

Add ids to Easel page sections for anchors

---

sections/easel-get-more.liquid

Add a vimeo url handling to consider url with more than 1 path in url path, and adapt to fit in the iframe path correctly
The vimeo url was crashing by change to a url with more than 1 path
Split the patch in different variables and mount according the url pattern expected by iframe
None

fix: handle vimeo url

---

sections/xcp-navbar.liquid
templates/page.x-carve-faq.json
templates/page.x-carve-pro-faq.json
templates/page.x-carve-pro-overview.json
templates/page.x-carve-tech-specs.json
templates/page.xcp-financing.json
templates/page.xcp-use-cases-cabinets.json
templates/page.xcp-use-cases-furniture.json
templates/page.xcp-use-cases-home-decor.json
templates/page.xcp-use-cases-signs.json
templates/product.x-carve-pro-4x2-product.json

**What does this PR do?**
Makes the text of the "Schedule a Call" button editable.
This had been working for the mobile sub-nav, but it was hardcoded in the desktop sub-nav.
**Background Context and Screenshots**
**What steps did you take to test your changes?**
Tested against the Production Store using `shopify theme serve`
**Link to the relevant Github Issue**
Closes https://github.com/inventables/fbolt/issues/6341
---
**Does anything need to be done before or after deploying this?**
**Who needs to be notified about these changes?**

Use block setting for Calendly button text on desktop

---

assets/cookie-banner.css
config/settings_schema.json
layout/easel.liquid
layout/theme.liquid
layout/xcp.liquid
sections/cookie_banner.liquid

**What does this PR do?**
Implements a cookie banner on the Shopify Online Store.
- Shows the banner if a cookie named `_inv_read_cookie_policy_at` has not been set
- If it has not been set:
- Set it
- And also call `setTrackingConsent`, to set the `'analytics'`, `'marketing'`, and `'preferences'` signals to `true`
- When the visitor clicks "OK", dismiss the banner
In the Theme Editor:
- Allows editing of the cookie banner text (HTML) and the button
- Includes a checkbox to show or hide the banner in the editor
**Background Context and Screenshots**
https://github.com/inventables/ecomm-theme-dawn/assets/26750330/e519e31a-66f3-4a44-b5c9-a1f63510e8fd
https://github.com/inventables/ecomm-theme-dawn/assets/26750330/eada2f9b-565e-4d33-ba73-26cc0fdaca6d
Review the [design review …

Add Cookie Banner to Shopify

---

sections/shopify-login.liquid
templates/customers/login.json

This changes the login page to redirect to site.inventables.com for login rather than load the login form in the iframe. 
We want to remove steps in the checkout process. 
Using shopify theme dev and running fbolt locally, I:
- Logged out. Added items to my cart. Saw that I was directed to login. Logged in. Saw that I was on the checkout page
- Logged out. Added items to my cart. Saw that I was directed to login. Created a new account. Saw that I was on the checkout page
- On the checkout page, clicked `logout`. Saw that I was prompted to login. Logged in. Saw that I was back to the checkout page. 
- On shopify, went to `https://{store}/account/login`. Verified I was logged out on fbolt (observing the navbar). Logged in. Saw that I was sent to the cart page (the default with no return_to …

change login process to be a redirect

---

sections/cookie_banner.liquid

**What does this PR do?**
This change allows for the customerPrivacy API to be called even if a visitor has already seen the cookie banner on a different Inventables property For example:
- Visitor visits easel.inventables.com
- Visitor sees the banner and the _inv_read_cookie_policy_at cookie is set
- Visitor visits inventables.com
- _inv_read_cookie_policy_at is already set, so the banner is not shown
- The visitor's currentVisitorConsent had not been set, so we call setTrackingConsent to register those signals
**Background Context and Screenshots**
@rodovich pointed out that if a visitor starts on a different property (such as the Forum or Easel), they will have seen the cookie banner, so when they visit the Shopify store they will neither see the banner a second time, nor have their …

Register customer privacy signals independently of the cookie banner

---

sections/main-cart-footer.liquid

This PR removes the express checkout options from the cart page. 
Before: 
After:

Remove express checkout buttons from cart page

---

sections/cookie_banner.liquid

This applies the change from https://github.com/inventables/easel/pull/10069 to set the cookie banner cookie's `path` to allow it to be read from any paths on our domain—by default cookies are scoped to the beginning part of the path of the page where they're set (e.g. `/products` when set from a product page). Also sets `max-age` to 365 days so that the cookie outlasts the session.
Depending on the initial landing page where the cookie banner cookie is set, the banner can appear again later. For example:
1. In a new browser or private/incognito tab, visit https://www.inventables.com/products/x-carve-1.
2. Notice the cookie banner.
3. Click "Add to cart".
4. The cart page shows the cookie banner again.
I tested the same code changes in Easel using the dev tools, as described in …

Fix propagation of cookie banner between pages
